datamodule:
  _target_: uncertainty_modeling.toy_datamodule_3D.ToyDataModule3D
  dataset_name: Case_1
  num_raters: 3
  data_num_folds: 5
  data_fold_id: 0
  batch_size: 8
  patch_size: 64
  patch_overlap: 1
  num_workers: 8
  seed: 123
model:
  _target_: uncertainty_modeling.models.unet3D_module.UNet3D
  num_classes: 2
  in_channels: 1
  initial_filter_size: 8
  kernel_size: 3
  do_instancenorm: true
exp_name: Softmax-Case-1
version: null
data_input_dir: /home/${oc.env:USER}/Uncertainty/ToyData
save_dir: /home/${oc.env:USER}/Uncertainty/ToyExperiments
seed: 123
max_epochs: 50
batch_size: 8
learning_rate: 0.0003
weight_decay: 1.0e-05
gpus: '1'
logger:
  _target_: pytorch_lightning.loggers.TensorBoardLogger
  save_dir: ${save_dir}
  name: ${exp_name}
progress_bar:
  _target_: pytorch_lightning.callbacks.TQDMProgressBar
  refresh_rate: 10
